name: Update subtree repos
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v2
        with:
          # Need to fetch all the history for the subtree commands to work
          fetch-depth: 0
      - name: Setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Update subtree repos
        run: ./update-repos.sh
      - name: Push changes
        run: git push
